### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mahdiciven** [Kucoin/kucoin-python-sdk#101]
Following is my whole code:
`from kucoin.client import Market`
`client = Market(url='https://api.kucoin.com')`

`klines = client.get_kline('BTC-USDT','1min')`
`print(klines)`

and it gives this error:
ImportError: cannot import name 'Market' from 'kucoin.client'

apparently 'kucoin.client' doesn't have 'Market'

**Comment by DavidEBrumbaugh** [comment]
@mahdiciven apparently the class is MarketData

**Comment by ISAAC-XXYYZZ** [comment]
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
