### ISSUE TITLE
404 on Sandbox on query_isolated_margin_account_info() 

### ISSUE THREAD

**Issue by DavidEBrumbaugh** [Kucoin/kucoin-python-sdk#102]
On `Margin.query_isolated_margin_account_info() `  I'm getting `Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}`  

I have not tried it on production, yet.

**Comment by ISAAC-XXYYZZ** [comment]
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
