### ISSUE TITLE
'holds' asset question

### ISSUE THREAD

**Issue by 462960** [Kucoin/kucoin-python-sdk#106]
'https://api.kucoin.com/api/v1/accounts' returns data as depicted: [{'id': '649c5..........56e6', 'currency': 'STX', 'type': 'main', 'balance': '23', 'available': '23', 'holds': '0'}].
I'm interested in retrieving the amount of the deposited but temporarily unavailable asset.
1) What's the meaning of 'holds' in the presented response if it's 0 even if I can observe a temporarily unavailable deposit on my user's page?
2) I haven't found an endpoint to retrieve a temporarily unavailable deposit. Does it exist?

**Comment by progressivehed** [comment]
Hello. 

This is Hed (API Community manager of KuCoin).

Regarding your first question, the 'holds': '0' parameter here indicates that there is not any assets involve in trading or placing orders. Hold here refers to that part of your balance that is getting involve in your trading and going to be freeze for that purpose by system automatically.

**According to Doc:**

FUNDS ON HOLD
When placing an order, the funds for the order will be frozen . The froze funds cannot be used for other order placement or withdrawal and will remain on hold until the order is filled or cancelled.

https://docs.kucoin.com/#list-accounts

for your second question, if by temporarily unavailable deposit, you mean that part of deposit that not yet been received, we don't have that one

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
