### ISSUE TITLE
Cannot install into pipedream workflow

### ISSUE THREAD

**Issue by UFBMZ** [Kucoin/kucoin-python-sdk#107]
Using magic comment
"# pipedream add-paackage kucoin-python"
import Kucoin

still returns error "ModuleNotFound: Kucoin"

help

**Comment by ISAAC-XXYYZZ** [comment]
The error message "ModuleNotFound: Kucoin" indicates that the Kucoin package is not installed in your Python environment. The magic comment you mentioned ("# pipedream add-paackage kucoin-python") appears to be a typo and doesn't follow standard methods for installing packages in a Jupyter notebook or Python script.

To install the Kucoin package, you should use the following method in a Jupyter notebook:

```python
!pip install kucoin-python
```
After installing the package, you can import it with:


```python
from kucoin.client import Client
```

If you encounter any issues, feel free to provide feedback.
