### ISSUE TITLE
Unkown error for create_market_order

### ISSUE THREAD

**Issue by Ariosi** [Kucoin/kucoin-python-sdk#11]
this issue occurs for any size:

Code > order_id = client.create_market_order('BTC-USDT', 'buy' , size = '1')
Response > 200-{"code":"300000","msg":"Order price invalid."}

I test it with the sandbox key.
no problem with create_limit_order has been seen.

**Comment by 1bazinga25** [comment]
When you create a market order, you should add a parameter "type='market'" to place the order.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has had no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
