### ISSUE TITLE
Is there something wrong with the checksums for historical data?

### ISSUE THREAD

**Issue by Niqnil** [Kucoin/kucoin-python-sdk#112]
I downloaded some files from https://historical-data.kucoin.com/index.html?prefix=data/spot/daily/trades/ETHUSDT/ and https://historical-data.kucoin.com/index.html?prefix=data/spot/daily/trades/BTCUSDT/.

Using Konsole on Ubuntu 22.04:
```
$ sha256sum -c ETHUSDT-trades-2024-02-20.zip.CHECKSUM
sha256sum: ETHUSDT-trades-2024-02-20.zip.CHECKSUM: no properly formatted SHA256 checksum lines found
$ sha256sum -c btcusdt-trades-2022-12-31.zip.CHECKSUM
sha256sum: btcusdt-trades-2022-12-31.zip.CHECKSUM: no properly formatted SHA256 checksum lines found
```

**Comment by ISAAC-XXYYZZ** [comment]
Please use the following command:
md5sum -c ETHUSDT-trades-2024-02-20.zip.CHECKSUM
