### ISSUE TITLE
Missing setuptools in Requirements.txt

### ISSUE THREAD

**Issue by Chukeho** [Kucoin/kucoin-python-sdk#113]
Requirements.txt doesn't say you also need to install the package setuptools only says requests & websockets.

Idk if this is even a issue that is missing, just something I ran into the first time coding a project with this SDK, also idk if this is where you would even post about a issue like this...

**Comment by ISAAC-XXYYZZ** [comment]
If you're only developing and running Python source code locally and don't plan to package, release, or distribute the code to others, you typically don't need to use setuptools. The primary purpose of setuptools is for packaging, distributing, and installing Python projects.
