### ISSUE TITLE
Trade history

### ISSUE THREAD

**Issue by BurkhalterY** [Kucoin/kucoin-python-sdk#122]
Hi,

Is there an endpoint to get trade history? I looked in the docs and I found [that](https://www.kucoin.com/support/14047696578841), but nothing with the API.

Thanks in advance for your help!

Regards,
Yannis

**Comment by ISAAC-XXYYZZ** [comment]
he documentation can be found here: [KuCoin REST API - Spot Trading Orders: Get Order List](https://www.kucoin.com/docs/rest/spot-trading/orders/get-order-list). Similarly, you can find the documentation for margin trading and futures trading in their respective sections. Please review them step by step.

As for the API, please use methods like trade.get_order_list, trade.get_recent_orders, trade.get_order_details, etc.

**Comment by BurkhalterY** [comment]
Thanks! So I can only get trades from the 6 last months. No problem, I will pass by a CSV.
