### ISSUE TITLE
运行出现错误的一些说明，解决各种bug问题指示贴

### ISSUE THREAD

**Issue by sunshe35** [Kucoin/kucoin-python-sdk#14]
截止到：2021年3月18日

**首先这玩意需要翻墙，不翻墙获取不到数据。**
解决好翻墙问题，配置好

> api_key = '<api_key>'
> api_secret = '<api_secret>'
> api_passphrase = '<api_passphrase>'

之后，第一个demo就能够正常获取。

关于第二个demo(Websockets)，使用如下代码可以正确运行：
```python
import asyncio
from kucoin.client import WsToken
from kucoin.ws_client import KucoinWsClient

async def main():
    async def deal_msg(msg):
        if msg['topic'] == '/spotMarket/level3:BTC-USDT':
            print(msg)
        elif msg['topic'] == '/spotMarket/level3:KCS-USDT':
            print(msg)

    # is public
    client = WsToken()
    ws_client = await KucoinWsClient.create(None, client, deal_msg, private=False)

    await ws_client.subscribe('/spotMarket/level3:BTC-USDT,KCS-USDT')
    while True:
        await asyncio.sleep(5, loop=loop)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**这个案例有如下几点需要注意：**    
1、案例没有及时更新， /market/level3:   要改为   /spotMarket/level3:
2、要使用共有频道，其他频道存在一定的问题，比如说私有频道只能获取与自己相关的订单数据，所以如果你自己没有触发订单的话就什么数据也获取不了；使用沙盒模式由于沙盒模式成交非常的清淡，所以获取的数据很少，你要等很久才能获取一些交易订单信息。共有频道可以获取所有交易订单的实时信息，这个不存在上面的问题。

最后，感谢KuCoin官方团队成员(微信号：API_KuCoin01)给我的帮助，这才解决以上问题。

**Comment by Abdulrahman2274** [comment]
https://www.kucoin.com/promotions/sharea1000000USDTprizepool?rcode=QBSZ8EZX&utm_source=promotions_sharea1000000USDTprizepool

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has had no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
