### ISSUE TITLE
client.get_kline() will only return datetimes from 1970

### ISSUE THREAD

**Issue by IanFLee** [Kucoin/kucoin-python-sdk#16]
Even if I include a correct startAt parameter, all the klines returned have dates from 1970, almost like the start time has been hard-coded to 0. I'm not using the sandbox, I'm trying to get real, current data.

**Comment by roboticperception** [comment]
Hey @IanFLee were you able to figure this out?  I'm getting the same issue.  And when I set the startAt and endAt fields then I get a code 200000.
