### ISSUE TITLE
get_atomic_order in kucoin.client.Market is not working

### ISSUE THREAD

**Issue by 5erpens** [Kucoin/kucoin-python-sdk#17]
The issue is self-explanatory. When you run `get_atomic_order` for any symbol, you get 404-{"code":"404","msg":"not exist"}.
https://github.com/Kucoin/kucoin-python-sdk/blob/9c4190c86fb749b945c0e7c4995b6b03b2c53359/kucoin/market/market.py#L178
![image](https://user-images.githubusercontent.com/11454759/114289456-fd7ff180-9a6f-11eb-979a-14f35bd81691.png)

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation. https://www.kucoin.com/docs/beginners/introduction
Please try updating to the latest version of the SDK and modify your code to try again.
If you encounter any issues, feel free to provide feedback.
