### ISSUE TITLE
marketClient.get_symbol_list() returns nothing when specifying the market

### ISSUE THREAD

**Issue by devamin** [Kucoin/kucoin-python-sdk#18]
code :
```
marketClient.get_symbol_list(market='REQ-ETH')
```
res : 
```
{'code': '200000', 'data': []}
```

**Comment by quantumpacket** [comment]
@devamin you're passing the wrong value. You are passing a trading pair as the `market` value, you need to be passing one of the following:  

> BTC
KCS
USDS _(SC has been changed to USDS)_
ALTS _(ALTS market includes ETH, NEO, TRX)_

Docs:
- https://docs.kucoin.com/#parameters-39
- https://docs.kucoin.com/#get-market-list

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
