### ISSUE TITLE
Cancel order error

### ISSUE THREAD

**Issue by ffbboy30** [Kucoin/kucoin-python-sdk#22]
Hi,
I'm trying to implement an order cancel test.
The order works fine
`Trade_client = Trade(key=api_key, secret=api_secret, passphrase=api_passphrase, is_sandbox=False, `url='')
order_id = Trade_client.create_market_order('NANO-USDT', 'buy', size='1')`

I wait 5 second and I make a cancel order to stop it
`Trade_client.cancel_order(order_id['orderId'])`
and I've an error
`200-{"code":"400100","msg":"order_not_exist_or_not_allow_to_cancel"}`

Could you help me.
Thanks

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation: https://www.kucoin.com/docs/beginners/introduction
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
