### ISSUE TITLE
where is the documentation?

### ISSUE THREAD

**Issue by x011** [Kucoin/kucoin-python-sdk#23]
where is the documentation?

**Comment by d3vr** [comment]
Can't seem to find it either

**Comment by skittixch** [comment]
try this
https://readthedocs.org/projects/python-kucoin/downloads/pdf/latest/

**Comment by quantumpacket** [comment]
@skittixch that belongs to this project: https://github.com/sammchardy/python-kucoin

The APIs do not match.

**Comment by ISAAC-XXYYZZ** [comment]
For detailed documentation, please refer to:
https://www.kucoin.com/docs/beginners/introduction
