### ISSUE TITLE
Margin Orders?

### ISSUE THREAD

**Issue by slhawk98** [Kucoin/kucoin-python-sdk#24]
Are margin orders allowed? If so, what's the syntax?
I see magin.py file but not sure how to call functions within that file.

**Comment by sparkmobi** [comment]
+1

**Comment by codewc** [comment]
> Are margin orders allowed? If so, what's the syntax? I see magin.py file but not sure how to call functions within that file.


```
from kucoin.client import Trade
client = Trade(key='', secret='', passphrase='', is_sandbox=False)

order =client.create_limit_margin_order(
            symbol='KCS-USDT',
            side='buy',
            size='0.01',
            price='0.001',
            clientOid=get_uuid(),
            remark='test create_market_margin_order',
        )
        
 ```

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
