### ISSUE TITLE
futures stop limit

### ISSUE THREAD

**Issue by zholbrook** [Kucoin/kucoin-python-sdk#34]
Does the futures API have a stop limit order? I keep getting 404.

**Comment by codewc** [comment]
> Does the futures API have a stop limit order? I keep getting 404.
This is a `spot sdk`, please use `futures sdk ` [https://github.com/Kucoin/kucoin-futures-python-sdk](https://github.com/Kucoin/kucoin-futures-python-sdk)

**Comment by zholbrook** [comment]
Wrong repo
