### ISSUE TITLE
kucoin question

### ISSUE THREAD

**Issue by peter-zero00** [Kucoin/kucoin-python-sdk#38]
is there a way to get the favorites list using the api?  the list is stored remotely .it opens on phone and website. thanks

**Comment by codewc** [comment]
> is there a way to get the favorites list using the api? the list is stored remotely .it opens on phone and website. thanks

You need to encapsulate a web service yourself. 
After all, you need to configure your own API information to access your data.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
