### ISSUE TITLE
How to get KuCoin Trade Bot Transactions

### ISSUE THREAD

**Issue by sahayes1** [Kucoin/kucoin-python-sdk#40]
I really need a way to pull all the trades from my trade bots. Is there a way to do this? 

When I pull order history they are not included in that. 

Any help would be greatly appreciated!!

**Comment by codewc** [comment]
> I really need a way to pull all the trades from my trade bots. Is there a way to do this?
> 
> When I pull order history they are not included in that.
> 
> Any help would be greatly appreciated!!

This part of KuCoin Bot data cannot be queried through API for the time being, only spot and futures are supported

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
