### ISSUE TITLE
Instructions for Use

### ISSUE THREAD

**Issue by ocmich74** [Kucoin/kucoin-python-sdk#41]
I have everything setup but don't know how to run the program.  Are there instructions on what to do once API is connected?

**Comment by codewc** [comment]
> I have everything setup but don't know how to run the program. Are there instructions on what to do once API is connected?

There are instructions
https://github.com/Kucoin/kucoin-python-sdk#quick-start

**Comment by ISAAC-XXYYZZ** [comment]
Please refer to the example at https://github.com/Kucoin/kucoin-python-sdk/tree/master/kucoin/example
If you need any further assistance, feel free to ask!
