### ISSUE TITLE
Can't withdraw on alternative chain

### ISSUE THREAD

**Issue by EUA** [Kucoin/kucoin-python-sdk#42]
For example AVAX-C chain
`kcn.api_user.apply_withdrawal(currency='AVAX', address=Address, amount=Amount, chainId='avaxc')`
returns:
`Exception: 200-{"code":"400100","msg":"Incorrect withdrawal address"}  `
I tried with 'AVAXC', 'AVAX-C' and others without success, while address is correct for AVAX-C coin...

**Comment by ISAAC-XXYYZZ** [comment]
Please first try entering the correct network and address on the web or app. Once successful, you can then try using the API call.
If you need any further assistance, feel free to ask!
