### ISSUE TITLE
How to find transfers from Main account to Trade account?

### ISSUE THREAD

**Issue by garagesteve1155** [Kucoin/kucoin-python-sdk#45]
It looks like get_deposit_list only pulls actual deposits into the whole account... I would like to gather the data for Transfers to and from Main/Trading accounts. Is this possible?

Thanks!

**Comment by SanchezCD** [comment]
I gave transfer privileges to my API, but I still can't transfer from the main account to the trading account,
Do you know how I can do it?


I use the following code but I don't know what is wrong with it
user.inner_transfer( currency='BNB', from_payer='MAIN', to_payee='TRADE', amount= '0.1' , clientOid='whatever' )

**Comment by SanchezCD** [comment]
> It looks like get_deposit_list only pulls actual deposits into the whole account... I would like to gather the data for Transfers to and from Main/Trading accounts. Is this possible?
> 
> Thanks!


I gave transfer privileges to my API, but I still can't transfer from the main account to the trading account,
Do you know how I can do it? 
Did you solve it?

I use the following code but I don't know what is wrong with it
user.inner_transfer( currency='BNB', from_payer='MAIN', to_payee='TRADE', amount= '0.1' , clientOid='whatever' )

**Comment by ISAAC-XXYYZZ** [comment]
The get_deposit_list API is only for retrieving deposit records and is not related to internal account transfers. For more details, refer to the documentation:
https://www.kucoin.com/zh-hant/docs/rest/funding/deposit/get-deposit-list

Currently, there is no query interface for internal account transfer records, but you can use the user.get_transferable interface to obtain transferable funds. For more details, refer to the documentation:
https://www.kucoin.com/zh-hant/docs/rest/funding/transfer/get-the-transferable
