### ISSUE TITLE
Inner Trasfer from MAIN to TRADE account 

### ISSUE THREAD

**Issue by SanchezCD** [Kucoin/kucoin-python-sdk#48]
I gave transfer privileges to my API, but I still can't transfer from the main account to the trading account,
Do you know how I can do it?

I use the following code but I don't know what is wrong with it
user.inner_transfer( currency='BNB', from_payer='MAIN', to_payee='TRADE', amount= '0.1' , clientOid='whatever' )

Error:
Exception: 200-{"code":"400100","msg":"from not in the given range"}

**Comment by SanchezCD** [comment]
I solve it as follows:

 user.inner_transfer( currency='BNB', from_payer='main', to_payee='trade', amount= '0.1' , clientOid='whatever' )

**Comment by ISAAC-XXYYZZ** [comment]
Yes, this interface can fulfill your requirements. For more detailed documentation, please refer to: https://www.kucoin.com/docs/rest/funding/transfer/inner-transfer
