### ISSUE TITLE
Kucoin exampel

### ISSUE THREAD

**Issue by kazemihossein33** [Kucoin/kucoin-python-sdk#49]

**Comment by kazemihossein33** [comment]
I like

**Comment by codewc** [comment]
Do you mean you need some examples?

**Comment by Sayberix** [comment]
Yes!

**Comment by ISAAC-XXYYZZ** [comment]
Please refer to the example code in this directory.
https://github.com/Kucoin/kucoin-python-sdk/tree/master/kucoin/example
