### ISSUE TITLE
BTC 永续和BTC季度合约 symbol是什么呀

### ISSUE THREAD

**Issue by danerlt** [Kucoin/kucoin-python-sdk#5]
BTC 永续和BTC季度合约 symbol是什么呀

**Comment by liuxiaohao** [comment]
您好，你这个是kucoin现货的sdk。 kucoin合约交易对的symbol如下  永续反向合约 XBTUSDM 永续正向合约 XBTUSDTM BTC季度合约 XBTMM20(20200626交割)  XBTMU20（20200925交割）

**Comment by danerlt** [comment]
@liuxiaohao 感谢解答,我在发明者社区看到了高频量化策略,想跑一下策略,现在提示服务器时间和客户端时间相差5秒,我用的VPS是韩国的VPS,是不是要换一个VPS再试

**Comment by 1bazinga25** [comment]
您好，我们建议您用AWS 日本。
