### ISSUE TITLE
read the docs page built incorrectly?

### ISSUE THREAD

**Issue by john-robert** [Kucoin/kucoin-python-sdk#52]
Hi folks,
The docs on https://python-kucoin.readthedocs.io/en/latest/general.html seem incomplete. For all paragraphs from "General Endpoints" on, no information is displayed at all. I suspect this shouldn't be the case. Is there any alternative documentation I should follow? Thank you for any hints.

**Comment by codewc** [comment]
This document and sdk are not officially maintained by KuCoin.
The official documentation is https://docs.kucoin.com/

**Comment by ISAAC-XXYYZZ** [comment]
Please use our official SDK. The detailed documentation can be found here.
https://www.kucoin.com/docs/beginners/introduction
If you need any further assistance, feel free to ask!
