### ISSUE TITLE
/api/v1/trade-fees?symbols=BTC-USDT error

### ISSUE THREAD

**Issue by Conteduca** [Kucoin/kucoin-python-sdk#61]
When I try executing the api call /api/v1/trade-fees?symbols=BTC-USDT I receive the following error
Exception: 400-{"code":"400001","msg":"Please check the header of your request for KC-API-KEY, KC-API-SIGN, KC-API-TIMESTAMP, KC-API-PASSPHRASE"}

Take into account that I am using the library and all other functions seem to work.

**Comment by progressivehed** [comment]
This endpoint requires authentication.

Please provide headers for this

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
