### ISSUE TITLE
 why I take wrong data and wrong timestamp

### ISSUE THREAD

**Issue by hossain93** [Kucoin/kucoin-python-sdk#65]
![Capture](https://user-images.githubusercontent.com/77359545/159427309-445ac107-5d76-485a-a4e9-d9455ea9baad.PNG)
![Capture](https://user-images.githubusercontent.com/77359545/159427481-e098fffb-a88f-463e-a263-e89ce787aa17.PNG)
**as you see I take different time**

**also when I use .KXBTUSDT I take wrong data**

![Capture](https://user-images.githubusercontent.com/77359545/159427898-80621256-76fa-40db-aa50-bce5bcff148f.PNG)
![Capture](https://user-images.githubusercontent.com/77359545/159428107-bfa4c7f1-9125-44ae-be91-36523da0fe4e.PNG)
 **can you help me**

**Comment by progressivehed** [comment]
Hi

Do you get delayed info?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has had no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
