### ISSUE TITLE
USDT from sell orders dissapear

### ISSUE THREAD

**Issue by OlMi1** [Kucoin/kucoin-python-sdk#66]
Running a sell order in the sandbox. The USDT that should appear never do so. What is happening there?

Example:

1. Before: 49,981 USDT, 0 BTC
2. Buy BTC for one USDT (ID `623df0a80091a600016e893e`)
3. New Balance: 49,980 USDT, 0.0002324 BTC
4. Sell all BTC available (ID `623df0e30091a600016e903f`)
5. Final balance: 49,980 USDT, 0 BTC

The JSON response when asking for trade details contains `'dealFunds': '0.004648'` making me wonder if it means that somehow double the sell amount are fees, stagnating the USDT Balance.

**Comment by Thisdude553** [comment]
did you test the order manually in the kucoin interface? I ran into a similar issue when manually trading because there is a minimum order size for selling

**Comment by progressivehed** [comment]
you should also consider the fee for your transaction.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
