### ISSUE TITLE
Building local orderbook

### ISSUE THREAD

**Issue by thephilippk** [Kucoin/kucoin-python-sdk#68]
I am able to get a Rest-API snapshot of an orderbook. I built the logic to update the orderbook-snapshot from the Rest-API with updates from the Websocket-API.
But I really struggle with the calibration procedure. How can I combine the continuous data stream, from the right msg onwards, with the snapshot? I did not succeed in feeding both the msg and the orderbook in my function "update orderbook".

Thx a lot

**Comment by progressivehed** [comment]
Calibration procedure：

After receiving the websocket Level 2 data flow, cache the data.
Initiate a [REST](https://docs.kucoin.com/#get-full-order-book-aggregated) request to get the snapshot data of Level 2 order book.
Playback the cached Level 2 data flow.
Apply the new Level 2 data flow to the local snapshot to ensure that the sequence of the new Level 2 update lines up with the sequence of the previous Level 2 data. Discard all the message prior to that sequence, and then playback the change to snapshot.
Update the level2 full data based on sequence according to the price and size. If the price is 0, ignore the messages and update the sequence. If the size=0, update the sequence and remove the price of which the size is 0 out of level 2. For other cases, please update the price.

**Comment by progressivehed** [comment]
I will post an example code for python in [Learning center](https://t.me/kucoin_learning) soon.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
