### ISSUE TITLE
Kucoin has updated Get Account Ledgers 

### ISSUE THREAD

**Issue by dasalter** [Kucoin/kucoin-python-sdk#69]
Get Account Ledgers has been updated and the method used in this module is now deprecated and no longer works (https://docs.kucoin.com/#get-account-ledgers-deprecated)

Please can the module be updated with the current API call structure (https://docs.kucoin.com/#get-account-ledgers)

**Comment by progressivehed** [comment]
Hi

Are you using the SDK?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
