### ISSUE TITLE
Similar method as get_all_tickers but for different time ranges

### ISSUE THREAD

**Issue by td20002** [Kucoin/kucoin-python-sdk#77]
Can you add a function similar to get_all_tickers in market.py but it allows us to choose a specific time range like 1 hour instead of 24 hours?

**Comment by codewc** [comment]
> Can you add a function similar to get_all_tickers in market.py but it allows us to choose a specific time range like 1 hour instead of 24 hours?

Now it can only default to 24h, and does not support other.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
