### ISSUE TITLE
Exception: 400-{"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}

### ISSUE THREAD

**Issue by AdrianOM98** [Kucoin/kucoin-python-sdk#82]
I am trying to create a bot in python and I am using the python-kucoin-futures library. Every time I try to use the Trade module it throws me the exception:
Exception: 400-{"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}.

Can someone help me to solve it.
Thank you.

**Comment by ISAAC-XXYYZZ** [comment]
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
