### ISSUE TITLE
Stop loss and take profit

### ISSUE THREAD

**Issue by FirstVoyager** [Kucoin/kucoin-python-sdk#85]
Can i set take profit and stop loss to my orders?
is there any way?

**Comment by SirBricksALot** [comment]
Only way on KC that I know of would be to code your own OCO (one cancels other) which would require some routine ticker polling of the server to check price and then automatically post the single order according to either hi / low conditions. Binance has this built in from what I recall but KC is just better for some of us.

**Comment by ISAAC-XXYYZZ** [comment]
Sure, please check the document at https://www.kucoin.com/docs/rest/spot-trading/stop-order/place-order
For the API, please use create_limit_stop_order or create_market_stop_order and refer to the documentation to fill in the correct parameters.
If you need any further assistance, feel free to ask!
