### ISSUE TITLE
Margin order cannot add remarks

### ISSUE THREAD

**Issue by jaythequant** [Kucoin/kucoin-python-sdk#88]
When placing a margin order using the `POST /api/v1/margin/order`, the `remark` argument does not have any effect. I have found this to be true in a library I am developing, CCXT, this SDK and several other wrappers. As such, I believe remarks are simply not supported by the current margin order endpoint on KuCoin's server side. Remarks are listed as a parameter option in the official documentation and remarks do work for spot trade orders.

Can your team confirm whether remarks are intended to be supported? If remarks are not supported for margin trading, is there any intention to add them? Remarks substantially simplify my algorithm's order flow and reduce significantly REST API calls required.

Thank you.

**Comment by SirBricksALot** [comment]
Same issue here for a long time but glad I found your post. Was able to add remarks for Trade account at least. Hope they fix this for margin someday :/

**Comment by quantokenizer** [comment]
I can confirm this is still an issue with margin orders. The remark feature works for stop orders at least.

**Comment by ISAAC-XXYYZZ** [comment]
Sorry for the delayed response. We've already forwarded this request internally and it's currently under evaluation. Please keep an eye on our documentation for updates!
If you need any further assistance, feel free to ask!
