### ISSUE TITLE
Get the average price of a market order: get_order_details and get_fill_list

### ISSUE THREAD

**Issue by fashionprivate** [Kucoin/kucoin-python-sdk#90]
hello all,

I have a problem to retrieve the average price of a market order.
I retrieve the details of the order with get_order_details(orderId) but I figure out that sometimes dealFunds and dealSize fields are empty (even if the market order filled completely).

Is there anyone who experienced the same?

Then I tried to use get_fill_list(tradeType, orderId) to retrieve all the filled orders, but it doesn't work because I retrieve always an empty list. This is the response:
{"currentPage":1,"pageSize":50,"totalNum":0,"totalPage":0,"items":[]}

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
