### ISSUE TITLE
Ability to send orders through a private websocket

### ISSUE THREAD

**Issue by kheil117** [Kucoin/kucoin-python-sdk#91]
Hi all, 
Is it possible to send orders via a private WS rather than the ReST API ?
If so, what kind of trade message is Kucoin expecting ?
If not, can we add this feature ?
Reason I am asking is that I often get time out when sending large batches of orders simultaneously and I believe a WS would handle that better.
Thanks

**Comment by progressivehed** [comment]
Hello

1.Is it possible to send orders via a private WS rather than the ReST API ?
A: No it is not available now.

2. If not, can we add this feature ?
A: We may add this feature in future. It has been suggested.

**Comment by kheil117** [comment]
thank you
