### ISSUE TITLE
[Websocket] on minute close

### ISSUE THREAD

**Issue by AnimusXCASH** [Kucoin/kucoin-python-sdk#96]
Hi, 

can someone assist me how to get the close value of klines through websocket?

thank you.

**Comment by progressivehed** [comment]
Hello

When you subscribe to that topic, the response will look like this:

{
    "type":"message",
    "topic":"/market/candles:BTC-USDT_1hour",
    "subject":"trade.candles.update",
    "data":{
        "symbol":"BTC-USDT",    // symbol
        "candles":[
            "1589968800",   // Start time of the candle cycle
            "9786.9",       // open price
            **"9740.8",       // close price**
            "9806.1",       // high price
            "9732",         // low price
            "27.45649579",  // Transaction volume
            "268280.09830877"   // Transaction amount
        ],
        "time":1589970010253893337  // now（us）
    }
}

So in JSON response that you get, the third element in dic that you get would be the close price. In Python you can easily parse it by json.load()

**Comment by AnimusXCASH** [comment]
thank you.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed, we will now close it.
If you need any further assistance, feel free to ask!
