### ISSUE TITLE
cannot sell short

### ISSUE THREAD

**Issue by sq5rix** [Kucoin/kucoin-python-sdk#97]
cannot trade with borrowing in a margin account.

I get insufficient funds

**Comment by HamzLDN** [comment]
Same
Did you manage to get around it? Im trying to trade on the futures platform

**Comment by ISAAC-XXYYZZ** [comment]
Before trading, please refer to our documentation: [What is Crypto Margin Trading?](https://www.kucoin.com/support/900002211683)
and ensure that your margin account has a sufficient balance.
After manually opening an order on the web or app, try using the API. If you encounter any issues, feel free to provide feedback at any time.
